# Generated by Django 4.0.4 on 2023-08-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_room_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hotel',
            new_name='hotel_name',
        ),
    ]
